# -*- coding: utf-8 -*-
"""
/***************************************************************************
 sam_qgis
                                 A QGIS plugin
 This plugin allows you to use Segment Anything Model (SAM) by Meta with satellite imagery. Export your outputs as gpkg, geojson.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-28
        copyright            : (C) 2023 by Rodrigo B Santos
        email                : rodrigobrusts@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load sam_qgis class from file sam_qgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .segment_anything_qgis import sam_qgis
    return sam_qgis(iface)
